version: "3"

services:
  app:
    build: .
    env_file:
      - ./.env
    volumes:
      - ./logs:/pjserver-sys/logs:rw
    restart: always
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: "1"
